passm/routes.py
import csv
import io
import json
from datetime import datetime

from flask import Blueprint, render_template, request, redirect, url_for, flash, Response, session, jsonify

from .db import get_db
from .utils import (retrieve_vaults, get_resources_by_vault, encrypt_password, decrypt_password,
                    get_password_stats, login_required)

main = Blueprint('main', __name__)


@main.route('/resource/new', methods=['GET', 'POST'])
@login_required
def add_resource():
    vault_list = retrieve_vaults()
    if request.method == 'POST':
        resource_details = request.form
        resource = resource_details.get('name')
        username = resource_details.get('username')
        email = resource_details.get('email')
        password = resource_details.get('password')
        url = resource_details.get('url')
        vault_id = resource_details.get('vault-id')

        if resource and password and vault_id and email:
            db = get_db()
            cur = db.cursor()
            encrypted_password = encrypt_password(password)
            try:
                cur.execute("INSERT INTO resource (resource_name, resource_username,"
                            "resource_email, resource_url, creation_date)"
                            "VALUES (%s, %s, %s, %s, NOW())",
                            (resource, username, email, url))
                resource_id = cur.lastrowid

                cur.execute("""INSERT INTO password (encrypted_password, resource_id, 
                               creation_date, last_modified_date) 
                               VALUES (%s, %s, NOW(), NOW())""",
                            (encrypted_password, resource_id))

                cur.execute("INSERT INTO resource_vault (resource_id, vault_id) VALUES (%s, %s)",
                            (resource_id, vault_id))
                db.commit()
                flash('Resource added successfully', 'info')

                return redirect(url_for('main.add_resource'))
            except Exception as e:
                db.rollback()
                print("An error occurred:", e)
                flash('Failed to add resource', 'danger')
            finally:
                cur.close()
        else:
            flash('Please fill out all fields', 'danger')

    return render_template('add_resource.html', vaults=vault_list)


@main.route('/', defaults={'vault_id': None, 'resource_id': None})
@main.route('/password-list/', defaults={'vault_id': None, 'resource_id': None})
@main.route('/password-list/resource/<int:resource_id>', defaults={'vault_id': None})
@main.route('/password-list/vault/<int:vault_id>', defaults={'resource_id': None})
@main.route('/password-list/vault/<int:vault_id>/resource/<int:resource_id>')
@login_required
def view_password_list(vault_id, resource_id):
    # TODO: make a global cursor for not recreating same variables
    db = get_db()
    cur = db.cursor(dictionary=True)

    user_id = session.get('user_id')

    cur.execute("""
            SELECT u.username, u.email, uc.automatic_logout_time, uc.show_passwords_by_default
            FROM user u
            JOIN user_configuration uc ON u.id = uc.user_id
            WHERE u.id = %s
        """, (user_id,))
    user = cur.fetchone()
    cur.close()

    db = get_db()
    cur = db.cursor()

    selected_resource_id = None
    vault_name = None
    if resource_id:
        query = """SELECT resource.resource_id
                           FROM resource
                           INNER JOIN resource_vault ON resource.resource_id = resource_vault.resource_id
                           INNER JOIN vault ON vault.vault_id = resource_vault.vault_id
                           WHERE vault.user_id = %s AND resource.resource_id = %s"""
        cur.execute(query, (user_id, resource_id,))
        result = cur.fetchone()
        cur.close()
        if result:
            selected_resource_id = result[0]

    # Fetch resources based on the provided vault_id
    if vault_id is not None:
        resource_list = get_resources_by_vault(vault_id)
        db = get_db()
        cur = db.cursor()
        vault_name_query = "SELECT vault_name FROM vault WHERE vault_id = %s AND vault.user_id = %s"
        cur.execute(vault_name_query, (vault_id, user_id,))
        vault_name_result = cur.fetchone()
        if vault_name_result:
            vault_name = vault_name_result[0]  # Get the vault name
    else:
        resource_list = get_resources_by_vault()

    vault_list = retrieve_vaults()

    return render_template(
        'passwords_list.html',
        resources=resource_list,
        vaults=vault_list,
        selected_resource_id=selected_resource_id,
        vault_name=vault_name,
        user=user
    )


@main.route('/vault/new', methods=['GET', 'POST'])
@login_required
def add_vault():
    vault_list = retrieve_vaults()
    if request.method == 'POST':
        vault_details = request.form
        vault = vault_details.get('vault-name')
        description = vault_details.get('vault-description')

        if vault:
            db = get_db()
            cur = db.cursor()
            user_id = session.get('user_id')
            try:
                cur.execute("INSERT INTO vault (vault_name, vault_description, user_id) VALUES (%s, %s, %s)",
                            (vault, description, user_id))
                db.commit()
                flash('Vault added successfully', 'info')
                return redirect(url_for('main.add_vault'))
            except Exception as e:
                db.rollback()
                print("An error occurred:", e)
                flash('Failed to add vault', 'danger')
            finally:
                cur.close()

    return render_template('add_vault.html', vaults=vault_list)


@main.route('/')
@main.route('/home')
@login_required
def view_vaults():
    vault_list = retrieve_vaults()

    return render_template('layout.html', vaults=vault_list)


@main.route('/password-list/', defaults={'vault_id': None, 'resource_id': None}, methods=['POST'])
@main.route('/password-list/resource/<int:resource_id>', defaults={'vault_id': None}, methods=['POST'])
@main.route('/password-list/vault/<int:vault_id>', defaults={'resource_id': None}, methods=['POST'])
@main.route('/password-list/vault/<int:vault_id>/resource/<int:resource_id>', methods=['POST'])
@login_required
def manage_resource(resource_id=None, vault_id=None):
    db = get_db()
    cur = db.cursor(dictionary=True)

    if not resource_id:
        resource_id = request.form.get('resource-id')

    if request.form['action'] == 'update':
        if request.method == 'POST':
            resource_details = request.form
            resource_id = resource_details.get('resource-id')
            resource_name = resource_details.get('name')
            resource_username = resource_details.get('username')
            resource_email = resource_details.get('email')
            resource_url = resource_details.get('url')
            resource_password = resource_details.get('password')

            cur.execute("SELECT * FROM resource WHERE resource_id = %s", (resource_id,))
            resource = cur.fetchone()
            cur.execute("SELECT * FROM password WHERE resource_id = %s", (resource_id,))
            password = cur.fetchone()

            if resource and password:
                encrypted_password = encrypt_password(resource_password)

                # Add old password to password_history table
                cur.execute(
                    """INSERT INTO password_history (password_id, old_encrypted_password)
                       VALUES (%s, %s)""",
                    (password['password_id'], password['encrypted_password'])
                )

                sql_query_resource = """UPDATE resource
                               SET resource_name = %s,
                                   resource.resource_url = %s,
                                   resource_username = %s,
                                   resource_email = %s 
                               WHERE resource_id = %s"""
                resource_params = (resource_name, resource_url, resource_username, resource_email, resource_id)

                sql_query_password = """UPDATE password
                                        SET last_modified_date = NOW(),
                                        encrypted_password = %s
                                        WHERE resource_id = %s"""
                password_params = (encrypted_password, resource_id)

                cur.execute(sql_query_resource, resource_params)
                cur.execute(sql_query_password, password_params)
                db.commit()
                flash('Resource updated successfully!', 'success')
            else:
                flash('Resource not found. Update failed.', 'error')
    elif request.form['action'] == 'delete':
        if resource_id:
            query = """DELETE FROM resource WHERE resource_id = %s"""
            cur.execute(query, (resource_id,))
            db.commit()
            flash('Resource deleted successfully!', 'info')
        else:
            flash('Resource not found. Delete failed.', 'danger')

    return redirect(url_for('main.view_password_list'))


@main.route('/pass-monitor/')
@login_required
def view_password_statistics():
    vault_list = retrieve_vaults()
    (weak_password_list, okay_password_list, good_password_list,
     strong_password_list, repeated_password_list) = get_password_stats()

    return render_template('pass_monitor.html', vaults=vault_list,
                           weak_password_list=weak_password_list,
                           okay_password_list=okay_password_list,
                           good_password_list=good_password_list,
                           strong_password_list=strong_password_list,
                           repeated_password_list=repeated_password_list)


@main.route('/export/resources/', methods=['GET', 'POST'])
@login_required
def export_resources():

passm/templates/account_settings.html
{% extends "layout.html" %}
{% block content %}
<div class="">
    <main>
        <div class="user-settings-container">
            <h4 class="mb-3">Account settings</h4>

            <form class="needs-validation" novalidate>
                <div class="row g-3">
                    <!-- User Settings Form -->
                    <form id="user-settings-form">
                        <label for="username">Username</label>
                        <input type="text" id="username" name="username" value="{{ user.username }}"
                               class="form-control">

                        <label for="email">Email</label>
                        <input type="email" id="email" name="email" value="{{ user.email }}" class="form-control">

                        <hr class="my-4">

                        <!-- Additional settings -->
                        <div>Automatic Logout Time</div>
                        <select id="automatic-logout-time" name="automatic_logout_time" class="form-select">
                            <option value="30" {% if user.automatic_logout_time== 30 %}selected{% endif %}>30 min
                            </option>
                            <option value="60" {% if user.automatic_logout_time== 60 %}selected{% endif %}>1 hour
                            </option>
                            <option value="360" {% if user.automatic_logout_time== 360 %}selected{% endif %}>6 hours
                            </option>
                            <option value="1440" {% if user.automatic_logout_time== 1440 %}selected{% endif %}>24
                                hours
                            </option>
                        </select>

                        <div class="form-check mt-3">
                            <input class="form-check-input" type="checkbox" id="show-passwords-by-default"
                                   name="show_passwords_by_default" {% if user.show_passwords_by_default %}checked{%
                                   endif %}>
                            <label class="form-check-label" for="show-passwords-by-default">
                                Show passwords by default
                            </label>
                        </div>

                        <button type="submit" class="btn btn-primary mt-3">Save Changes</button>
                    </form>

                    <!-- 2FA Settings Form -->
                    <form method="POST" action="{{ url_for('auth.update_2fa') }}" id="2fa-form">
                        <input type="hidden" name="allow_2fa" value="off">
                        <div class="form-check mt-3">
                            <input class="form-check-input" type="checkbox" id="allow-2fa" name="allow_2fa"
                                   {% if user.status_2fa %}checked{% endif %}
                                   onchange="toggle2FA(this); submit2FAForm(this)">
                            <label class="form-check-label" for="allow-2fa">
                                Allow 2FA login
                            </label>
                        </div>
                    </form>

                    <!-- QR Code -->
                    <div id="qr-container" class="mt-3"
                         style="display: {% if user.status_2fa %}block{% else %}none{% endif %};">
                        <img class="qr-code-2fa" id="qr-code-2fa" src="{{ url_for('auth.generate_qr') }}"
                             alt="qr-code-2fa">
                    </div>
                </div>
            </form>


                <hr class="my-4">

                {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                <div class="mt-3 ml-3 mr-3">
                    {% for category, message in messages %}
                    <div class="alert alert-{{ category }} m-20 flash-message" role="alert">
                        {{ message }}
                    </div>
                    {% endfor %}
                </div>
                {% endif %}
                {% endwith %}

<!--                <div class="d-flex align-items-center justify-content-between" id="deactivate">-->
<!--                    <div>-->
<!--                        <b>Deactivate your account</b>-->
<!--                        <p>Details about your account and passwords</p>-->
<!--                    </div>-->
<!--                    <div class="ml-auto">-->
<!--                        <button class="btn btn-outline-danger ml-5">Deactivate</button>-->
<!--                    </div>-->
<!--                </div>-->
        </div>
    </main>
</div>

<script>
    const user = {{ user | tojson }};
</script>

{% endblock content %}

passm/templates/add_resource.html
{% extends 'layout.html' %}
{% block content %}
    <div class="form-wrapper">
        <form action="" method="post">
            <div class="form-group mb-2">
                <label for="resource-field">Resource name</label>
                <input type="text" class="form-control" id="resource-field" placeholder="Enter resource"
                       name="name" autocomplete="off">
            </div>

            <div class="form-group mb-2">
                <label for="pass-field">Username</label>
                <input type="text" class="form-control" id="username-field" placeholder="Enter username"
                       name="username">
            </div>

            <div class="form-group mb-2">
                <label for="pass-field">Email</label>
                <input type="text" class="form-control" id="email-field" placeholder="Enter email"
                       name="email">
            </div>

            <div class="form-group mb-2">
                <label for="pass-field">Password</label>
                <input type="password" class="form-control" id="pass-field" placeholder="Password"
                       name="password">
            </div>

            <div class="form-group mb-2">
                <label for="url-field">Resource URL</label>
                <input type="text" class="form-control" id="url-field" placeholder="Enter URL"
                       name="url" autocomplete="off">
            </div>

            <select class="form-select mb-3" aria-label="Vault select menu" name="vault-id">
                {% if vaults %}
                {% for vault in vaults %}
                    <option value="{{ vault.id }}" {% if loop.first %}selected{% endif %}>
                        {{ vault.name }}
                    </option>
                {% endfor %}
                {% else %}
                    <option selected disabled>No vaults available</option>
                {% endif %}
            </select>

            <button type="submit" class="btn btn-primary">Add</button>
        </form>
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                <div class="mt-3">
                    {% for category, message in messages %}
                        <div class="alert alert-{{ category }}" role="alert">
                            {{ message }}
                        </div>
                    {% endfor %}
                </div>
            {% endif %}
        {% endwith %}
    </div>
{% endblock content %}

passm/templates/add_vault.html
{% extends 'layout.html' %}
{% block content %}
    <div class="form-wrapper">
        <form action="" method="post">
            <div class="form-group mb-2">
                <label for="vault-field">Vault name</label>
                <input type="text" class="form-control" id="vault-field" placeholder="Enter vault"
                       name="vault-name" autocomplete="off">
            </div>

            <div class="form-group mb-2">
                <label for="description-field">Description</label>
                <input type="text" class="form-control" id="description-field" placeholder="Description"
                       name="vault-description" autocomplete="off">
            </div>

            <button type="submit" class="btn btn-primary">Add</button>
        </form>
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                <div class="mt-3">
                    {% for category, message in messages %}
                        <div class="alert alert-{{ category }}" role="alert">
                            {{ message }}
                        </div>
                    {% endfor %}
                </div>
            {% endif %}
        {% endwith %}
    </div>
{% endblock content %}

passm/templates/export.html
{% from "modals/modal.html" import modal %}

{% extends "layout.html" %}
{% block content %}
<div class="d-flex flex-column export-group">
    <div class="p-3 d-flex flex-column">
        <h4>Export</h4>
        <hr>
        <h6>File format</h6>
        <form method="POST" action="{{ url_for('main.export_resources') }}" class="d-flex flex-column">
            <div class="form-check">
                <input class="form-check-input" type="radio" name="format" id="format_json" value="json">
                <label class="form-check-label" for="format_json">
                    JSON
                </label>
            </div>
            <div class="form-check">
                <input class="form-check-input" type="radio" name="format" id="format_csv" value="csv" checked>
                <label class="form-check-label" for="format_csv">
                    CSV
                </label>
            </div>
            <button type="submit" name="action" class="btn btn-secondary mt-3">
                Export
            </button>
        </form>

        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        <div class="mt-3">
            {% for category, message in messages %}
            <div class="alert alert-{{ category }} flash-message mt-2" role="alert">
                {{ message }}
            </div>
            {% endfor %}
        </div>
        {% endif %}
        {% endwith %}
    </div>
    <!-- Button to trigger modal -->
    <button type="button" class="btn btn-outline-info mt-3 ml-3" data-bs-toggle="modal" data-bs-target="#exportLogModal">
      View Export Log
    </button>

    <!-- Modal -->
    {{ modal(
        id="exportLogModal",
        body="modals/modal_body_export_log.html",
        title="Export Log",
        footer_buttons=[
        {"type": "secondary", "label": "Close", "dismiss": True}
        ],
        data_to_pass=log_data
    ) }}
</div>
{% endblock content %}

passm/templates/export_log_body.html
<ul class="list-group">
  {% for log in data_to_pass %}
  <li class="list-group-item">
    <strong>Date:</strong> {{ log.export_date }} <br>
    <strong>File Type:</strong> {{ log.file_type }} <br>
    <strong>Exported Passwords:</strong> {{ log.num_of_exported_resources }}
  </li>
  {% else %}
  <li class="list-group-item">No export logs found.</li>
  {% endfor %}
</ul>

passm/templates/modal.html
{% macro modal(id, body, title, footer_buttons=None, data_to_pass=None) %}
<div class="modal fade" id="{{ id }}" tabindex="-1" aria-labelledby="{{ id }}Label" aria-hidden="true">
    <div class="modal-dialog modal-dialog-scrollable">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="{{ id }}Label">{{ title }}</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                {% include body %}
            </div>
            <div class="modal-footer">
                {% if footer_buttons %}
                {% for button in footer_buttons %}
                <button type="button" class="btn btn-{{ button.type }}" {% if button.dismiss %} data-bs-dismiss="modal"
                        {% endif %}>
                    {{ button.label }}
                </button>
                {% endfor %}
                {% else %}
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endmacro %}

passm/templates/passwords_list.html
{% from "modals/modal.html" import modal %}

{% extends "layout.html" %}
{% block content %}
<div class="d-flex flex-column flex-md-row pt-4 pb-4 pr-4 justify-content-center">
    {% if resources and resources|length > 0 %}
    <div class="list-group resource-list">
        {% if vault_name %}
        <h3>{{ vault_name }}</h3>
        {% else %}
        <h3>All resources</h3>
        {% endif %}
        <div class="input-group mb-3">
            {% if vault_name %}
            <input type="text" class="form-control search-resource-input"
                   placeholder="Search in {{ vault_name }}..." aria-label="resource-to-search"
                   aria-describedby="button-addon2">
            {% else %}
            <input type="text" class="form-control search-resource-input"
                   placeholder="Search in all vaults..." aria-label="resource-to-search"
                   aria-describedby="button-addon2">
            {% endif %}
            <button class="btn btn-outline-secondary" type="button" id="clear-button">
                <i class="bi bi-x"></i>
            </button>
        </div>

        <div class="list-group resource-list main-resource-list ml-0 mr-0">
            <form id="filter-form" class="mb-2">
                <!-- Date Range Filter -->
                <div class="d-flex">
                    <div class="date-start-group d-flex align-items-center">
                        <label for="date-start">Start Date:</label>
                        <input class="form-control" type="date" id="date-start">
                    </div>

                    <div class="date-end-group d-flex align-items-center">
                        <label for="date-end">End Date:</label>
                        <input class="form-control" type="date" id="date-end">
                    </div>
                </div>

                <!-- Password Length Filter -->
                <div class="d-flex min-password-length-group mt-2 align-items-center">
                    <label for="password-length-min">Min Password Length:</label>
                    <input class="form-control" type="number" id="password-length-min" min="0" value="0">
                </div>

                <div class="d-flex max-password-length-group mt-2 align-items-center">
                    <label for="password-length-max">Max Password Length:</label>
                    <input class="form-control" type="number" id="password-length-max" min="0" value="50">
                </div>
            </form>

            <!-- Sorting Dropdown -->
            <select class="form-select sorting-form mb-2" aria-label="Resource sorting">
                <option selected value="1" class="sorting-form-option">Newest to oldest</option>
                <option value="2" class="sorting-form-option">Oldest to newest</option>
                <option value="3" class="sorting-form-option">Alphabetical</option>
            </select>

            {% for id, resource in resources.items() %}
            <div href="#" class="resource-to-search list-resource-item list-group-item
                             resource-list-item list-group-item-action d-flex gap-3 py-3"
                 aria-current="true"
                 data-id="{{ id }}">

                <img src="{{ resource.resource_favicon }}"
                     alt="{{ resource.name }}"
                     width="32" height="32"
                     class="rounded-circle flex-shrink-0">

                <div class="pl-2 d-flex w-100 justify-content-between">
                    <div>
                        <h6 class="mb-0 resource-to-search-name">{{ resource.name }}</h6>
                        <p class="mb-0 opacity-75">{{ resource.email }}</p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>

    <div class="resource-info">
        <form action="{{ url_for('main.manage_resource') }}" method="POST" class="resource-form">
            <div class="d-flex flex-column">
                <div class="resource-info-header d-flex justify-content-between">
                    <input class="resource-name form-control pl-3 pt-3" name="name" value="" disabled>
                    <div class="resource-info-header-right">
                        <button type="button" class="btn btn-secondary edit-button">Edit
                        </button>
                        <button type="submit" name="action" value="update" class="btn btn-primary save-button"
                                style="display: none;">
                            Save
                        </button>
                        <button type="submit" name="action" value="delete" class="btn btn-danger delete-button">
                            Delete
                        </button>
                    </div>
                </div>
                <div class="list-group">
                    <div class="list-resource-item list-group-item resource-info-item d-flex flex-column">
                        <small class="d-block text-body-secondary">Username</small>
                        <input class="resource-username form-control resource-info-input" name="username"
                               value="" disabled>
                    </div>
                    <div class="list-resource-item list-group-item resource-info-item d-flex flex-column">
                        <small class="d-block text-body-secondary">Email</small>
                        <input class="resource-email form-control resource-info-input" name="email"
                               value="" disabled>
                    </div>

                    <div class="list-resource-item list-group-item resource-info-item d-flex flex-column">
                        <small class="d-block text-body-secondary">Password</small>
                        <div class="d-flex align-items-center">
                            <input class="resource-password form-control resource-info-input" name="password"
                                   type="{{ 'text' if user.show_passwords_by_default else 'password' }}"
                                   value="examplePassword" disabled="">
                            <button type="button" class="btn btn-outline-secondary toggle-password-btn"
                                    aria-label="Toggle password visibility">
                                <i class="bi {{ 'bi-eye-slash' if user.show_passwords_by_default else 'bi-eye' }}"></i>
                            </button>
                            <button type="button"
                                    class="btn btn-outline-secondary show-password-history-btn"
                                    aria-label="Show password history"
                                    data-bs-toggle="modal"
                                    data-bs-target="#passwordHistoryModal">
                                <i class="bi bi-clock-history"></i>
                            </button>
                        </div>
                        {{ modal(id="passwordHistoryModal",
                           title="Password History") }}
                    </div>

                    <div class="list-resource-item list-group-item resource-info-item d-flex flex-column">
                        <small class="d-block text-body-secondary">URL</small>
                        <input class="resource-url form-control resource-info-input" name="url"
                               value="" disabled>
                    </div>
                    <div class="list-resource-item list-group-item resource-info-item d-flex flex-column">
                        <small class="d-block text-body-secondary">Last Modified Date</small>
                        <input class="resource-modified-date form-control resource-info-input
                               resource-exception-date"
                               name="modified_date" value="" disabled>
                    </div>
                    <div class="list-resource-item list-group-item resource-info-item d-flex flex-column">
                        <small class="d-block text-body-secondary">Creation Date</small>
                        <input class="resource-creation-date form-control resource-info-input
                               resource-exception-date"
                               name="creation_date" value="" disabled>
                    </div>
                    <!-- Add resource ID -->
                    <input type="hidden" name="resource-id" class="resource-id-val" value="26">
                </div>
            </div>
        </form>
            {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
            <div class="mt-3 ml-3 mr-3">
                {% for category, message in messages %}
                <div class="alert alert-{{ category }} m-20 flash-message" role="alert">
                    {{ message }}
                </div>
                {% endfor %}
            </div>
            {% endif %}
            {% endwith %}
    </div>
    {% else %}
    <div class="no-resources-container">
        {% if vault_name %}
        <h3>{{ vault_name }}</h3>
        {% else %}
        <h3>All resources</h3>
        {% endif %}
        <div class="alert alert-primary no-resources-alert" role="alert">
            <h4 class="alert-heading">No Resources Found</h4>
            <p>There are no resources available at the moment. Please add some resources to view them here.</p>
        </div>
    </div>
    {% endif %}
</div>

<script>
    const resources = {{ resources|tojson }}
    const selectedResourceId = {{ selected_resource_id|tojson }}
</script>
{% endblock content %}